# Generated by Django 5.2.11 on 2026-03-20 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.ImageField(upload_to="images/")),
                ("name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MOS", "Mean Opinion Score"),
                            ("2AFC", "Two-Alternative Forced Choice"),
                        ],
                        max_length=4,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("scale_min", models.IntegerField(default=1)),
                ("scale_max", models.IntegerField(default=5)),
                ("scale_min_label", models.CharField(default="Bad", max_length=100)),
                (
                    "scale_max_label",
                    models.CharField(default="Excellent", max_length=100),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "sampler",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("random", "Random"),
                            ("least_evaluated", "Least Evaluated First"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "studies",
            },
        ),
        migrations.CreateModel(
            name="MOSStimulus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mos_stimuli",
                        to="iqa.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "MOS stimulus",
                "verbose_name_plural": "MOS stimuli",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PairStimulus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "image_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "image_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "reference_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "reference_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="iqa.image",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pair_stimuli",
                        to="iqa.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "pair stimulus",
                "verbose_name_plural": "pair stimuli",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MOSResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stimulus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iqa.mosstimulus",
                    ),
                ),
            ],
            options={
                "unique_together": {("stimulus", "user")},
            },
        ),
        migrations.CreateModel(
            name="PairResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("A", "Image A"), ("B", "Image B")], max_length=1
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stimulus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iqa.pairstimulus",
                    ),
                ),
            ],
            options={
                "unique_together": {("stimulus", "user")},
            },
        ),
    ]
