# Generated by Django 5.2.11 on 2026-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="image_scale_factor",
            field=models.FloatField(
                default=1.0, help_text='Only used when image_sizing is "scaled".'
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="image_sizing",
            field=models.CharField(
                choices=[
                    ("fit_screen", "Fit to screen"),
                    ("original", "Original size"),
                    ("scaled", "Scaled by factor"),
                ],
                default="fit_screen",
                max_length=12,
            ),
        ),
    ]
