# Generated by Django 5.2.11 on 2026-03-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqa", "0002_study_image_scale_factor_study_image_sizing"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="mos_use_textbox",
            field=models.BooleanField(
                default=False,
                help_text="MOS mode: use a free-text input instead of score buttons.",
            ),
        ),
    ]
