# Generated by Django 5.2.11 on 2026-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqa", "0003_study_mos_use_textbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="zoom_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show a magnified overlay when hovering over images.",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="zoom_factor",
            field=models.FloatField(
                default=2.0, help_text="Magnification factor for the zoom overlay."
            ),
        ),
    ]
