# Generated by Django 5.2.12 on 2026-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqa", "0004_study_zoom_enabled_study_zoom_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="allow_self_export",
            field=models.BooleanField(
                default=False,
                help_text="Allow participants to download their own responses as a CSV.",
            ),
        ),
    ]
