# Generated by Django 5.2.12 on 2026-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iqa", "0005_allow_self_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="pair_shared_ref_layout",
            field=models.BooleanField(
                default=False,
                help_text="2AFC mode: lay out Image A, the shared reference, and Image B in a single row.  Requires reference_a == reference_b for each pair; pairs with mismatched references fall back to the classic layout.",
            ),
        ),
    ]
