# Generated by Django 6.0.6 on 2026-06-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqa', '0006_study_pair_shared_ref_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairresponse',
            name='display_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pairresponse',
            name='shown_image_a',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='pairresponse',
            name='shown_image_b',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='pairresponse',
            name='shown_reference_a',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='pairresponse',
            name='shown_reference_b',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='pairresponse',
            name='was_swapped',
            field=models.BooleanField(default=False),
        ),
    ]
