# Generated by Django 5.2.15 on 2026-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqa', '0007_pairresponse_display_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='use_local_mode',
            field=models.BooleanField(default=False, help_text='2AFC + shared-reference only: download the whole study to the browser and record answers locally with background sync, so every click is instant even on high-latency networks. The server stays the source of truth via idempotent upserts; unsynced answers resend on reload and on page close.'),
        ),
    ]
