# Generated by Django 5.2.15 on 2026-07-22 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqa', '0008_study_use_local_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pair_stimuli', models.ManyToManyField(blank=True, related_name='assignments', to='iqa.pairstimulus')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='iqa.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('study', 'user')},
            },
        ),
    ]
