# Generated by Django 5.2.15 on 2026-07-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqa', '0009_studyassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='mode',
            field=models.CharField(choices=[('MOS', 'Mean Opinion Score'), ('2AFC', 'Two-Alternative Forced Choice'), ('QC', 'Qualification (Yes/No)')], max_length=4),
        ),
        migrations.AlterField(
            model_name='study',
            name='use_local_mode',
            field=models.BooleanField(default=False, help_text='2AFC + shared-reference only: download the whole study to the browser and record answers locally with background sync, so every click is instant even on high-latency networks. The server stays the source of truth via idempotent upserts; unsynced answers resend on reload and on page close. QC studies always run this way, so the flag is ignored for them.'),
        ),
        migrations.CreateModel(
            name='QCStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='iqa.image')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='iqa.image')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_stimuli', to='iqa.study')),
            ],
            options={
                'verbose_name': 'QC stimulus',
                'verbose_name_plural': 'QC stimuli',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studyassignment',
            name='qc_stimuli',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='iqa.qcstimulus'),
        ),
        migrations.CreateModel(
            name='QCResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Y', 'Yes -- qualified'), ('N', 'No -- not qualified')], max_length=1)),
                ('shown_image', models.CharField(blank=True, max_length=512)),
                ('shown_reference', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iqa.qcstimulus')),
            ],
            options={
                'unique_together': {('stimulus', 'user')},
            },
        ),
    ]
